channels: 
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy
  - requests
  - pandas
  - matplotlib
  - tensorboardx
  - jupyterlab
  - pytorch
  - torchvision
  - cudatoolkit=10.0
  - pip:
    - opencv-python
    - tqdm
